version: "3"
services:
    app:
        image: python:3
        hostname: lilspider
        stdin_open: true
        tty: true
        working_dir: /usr/src/app
        command: /bin/bash -c "echo \"alias ll='ls -ahl --color'\" >> /root/.bashrc; make install; bash"
        volumes:
            - .:/usr/src/app
